# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Bounded cumulative sum
#' @description \code{cumsum_bounded} takes a numeric vector and applies
#'     upper and/or lower bounds while calculating the cumulative sum. Uses rcpp for speed.
#' @name cumsum_bounded
#' @useDynLib boundedcumsum
#' @importFrom Rcpp evalCpp
#'
#' @param x A numeric vector
#' @param lower Lower bound
#' @param upper Upper bound
#' @return res A numeric vector of the bounded cumulative sum
#' @details
#' \code{cumsum_bounded} takes a numeric vector and applies upper and or
#' lower bounds.
#' @export
#' @examples
#' # lower bound only
#' a = c(1, -2, 1, 1)
#' cumsum_bounded(a, lower = 1)
#'
#' # upper bound only
#' b = c(1, -2, 2, 1)
#' cumsum_bounded(b, upper = 1)
#'
#' # upper and lower bound
#' c = c(1, -2, 2, 1)
#' cumsum_bounded(c, lower = 0, upper = 2)
#'
NULL

cumsum_bounded <- function(x, upper = NULL, lower = NULL) {
    .Call('boundedcumsum_cumsum_bounded', PACKAGE = 'boundedcumsum', x, upper, lower)
}

